# Generated by Django 5.2.3 on 2025-07-09 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.CharField(default='/media/avatars/wrobel.png', max_length=50, null=True),
        ),
    ]
