# Generated by Django 5.2.3 on 2025-07-26 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_customuser_is_email_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_email_confirmed',
        ),
    ]
