# Generated by Django 6.0 on 2025-12-09 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_remove_customuser_is_email_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='protector',
            field=models.BooleanField(default=False),
        ),
    ]
