# Generated by Django 5.2.3 on 2025-07-01 08:37

import django.db.models.deletion
import photo.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('upload_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_private', models.BooleanField(default=True)),
                ('image', models.ImageField(null=True, upload_to=photo.models.upload_to_uuid)),
                ('prediction_1', models.TextField(null=True)),
                ('prediction_2', models.TextField(null=True)),
                ('prediction_pl', models.TextField(null=True)),
                ('owner_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
