# Generated by Django 5.2.1 on 2025-06-03 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('upload_time', models.DateTimeField()),
                ('is_private', models.BooleanField()),
            ],
        ),
    ]
