# Generated by Django 5.2.3 on 2025-07-09 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='custom_name',
            field=models.TextField(null=True),
        ),
    ]
