# Generated by Django 5.2.1 on 2025-06-04 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_photo_animal'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='owner_id',
            field=models.TextField(default=0),
        ),
    ]
