# Generated by Django 5.2.3 on 2025-07-02 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_photo_review_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='owner_id',
            new_name='owner',
        ),
    ]
