# Generated by Django 5.2.3 on 2025-08-06 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_photo_custom_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='localization_latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='localization_longitude',
            field=models.FloatField(null=True),
        ),
    ]
