# Generated by Django 6.0 on 2025-12-19 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0004_remove_photo_prediction_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='n_times_seen',
            field=models.IntegerField(default=0),
        ),
    ]
