# Generated by Django 5.2.3 on 2025-07-03 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0005_review_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='score',
        ),
        migrations.AddField(
            model_name='review',
            name='helpful',
            field=models.BooleanField(default=0),
        ),
    ]
